#!/opt/local/bin/python

#Configuration settings
PL_NUMCHANNELS = 9
PL_NUMSIDCHANNELS = 6   #3 for mono sid, 6 for stereo sid, or 9 for tripple sid...
PL_ZPSTART = 2

#Variable init
zpcounter = PL_ZPSTART
playerfile = ""
datafile = ""


#Generate data file
datafile += "; droneMON PLAYER DATA\n"
datafile += "\n"
datafile += "pl_seqptrs_lo:\n"
datafile += "   !byte 0\n"
datafile += "\n"
datafile += "pl_seqptrs_hi:\n"
datafile += "   !byte 0\n"
datafile += "\n"
for i in range(PL_NUMCHANNELS):
    datafile += "pl_v"+str(i).zfill(2)+"_seqlist:\n"




#Generate code file
playerfile += "; droneMON PLAYER CODE\n"
playerfile += "\n"
playerfile += "; This file is autogenerated by py_makeplayer.py and deleted when issuing a make clean,\n"
playerfile += "; so please don't mess with it directly. Make changes in the python script instead.\n"
playerfile += "\n"
playerfile += ";============================\n"
playerfile += ";Config constants\n"
playerfile += "\n"
playerfile += "PL_NUMCHANNELS = "+str(PL_NUMCHANNELS)+"\n"
for i in range(PL_NUMCHANNELS):
    playerfile += "PL_ZP_VP"+str(i).zfill(2)+" = $"+'{:02X}'.format(zpcounter)+"\n"
    zpcounter += 2
playerfile += "PL_ZP_SONGPOS = $"+'{:02X}'.format(zpcounter)+"\n"
zpcounter += 1
playerfile += "PL_ZP_SEQBREAKFLAG = $"+'{:02X}'.format(zpcounter)+"\n"
zpcounter += 1
playerfile += "\n"
playerfile += ";============================\n"
playerfile += "pl_main:\n"
playerfile += "\n"


playerfile += "	;---------------------------\n"
playerfile += "	; Sequence parsing\n"
playerfile += "\n"
playerfile += "		;First check for the sequence break flag\n"
playerfile += "		lda PL_ZP_SEQBREAKFLAG\n"
playerfile += "		bne .noseqbreak\n"
playerfile += "\n"
playerfile += "			;Time to fetch a new sequence pointer\n"
playerfile += "			inc PL_ZP_SONGPOS	;Bump to next\n"
playerfile += "			ldy PL_ZP_SONGPOS\n"
playerfile += "\n"

for i in range(PL_NUMCHANNELS):
    playerfile += "			;Fetch pointer for v"+str(i).zfill(2)+"\n"
    playerfile += "			lax pl_v"+str(i).zfill(2)+"_seqlist,y\n"
    playerfile += "			lda pl_seqptrs_lo,x\n"
    playerfile += "			sta PL_ZP_VP"+str(i).zfill(2)+"\n"
    playerfile += "			lda pl_seqptrs_hi,x\n"
    playerfile += "			sta PL_ZP_VP"+str(i).zfill(2)+"+1\n"
    playerfile += "\n"
playerfile += "			;Clear seqbreakflag\n"
playerfile += "			inc PL_ZP_SEQBREAKFLAG\n"
playerfile += "\n"
playerfile += ".noseqbreak:\n"
playerfile += ";---\n"
playerfile += "\n"
playerfile += "		;Iterate over all the channels and parse them\n"
# playerfile += "        ldx #PL_NUMCHANNELS-1\n"
for i in range(PL_NUMCHANNELS):
    playerfile += "xyz\n"
playerfile += "\n"



playerfile += "		rts\n"
playerfile += "		;---\n"
playerfile += "\n"
playerfile += "\n"
playerfile += ";============================\n"
playerfile += "pl_init:\n"
playerfile += "		rts\n"
playerfile += "		;---\n"
playerfile += "\n"




text_file = open("pl_main.a", "w")
text_file.write(playerfile)
text_file.close()

text_file = open("pl_data.a", "w")
text_file.write(datafile)
text_file.close()